# This is a basic workflow to help you get started with Actions

name: Docker build and push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: version
        run: |
          export VERSION=$(git rev-parse --short ${GITHUB_SHA})
          echo "::set-env name=VERSION::${VERSION}"
          export ARTIFACT_ID=$(cat package.json | grep name | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo "::set-env name=ARTIFACT_ID::${ARTIFACT_ID}"
      - name: docker build
        run: docker build --tag docker.pkg.github.com/${{ secrets.REPOSITORY }}/${ARTIFACT_ID}:${VERSION} .

      - name: docker push github
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
          docker push docker.pkg.github.com/${{ secrets.REPOSITORY }}/${ARTIFACT_ID}:${VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
